name: material3_layout
description: This package helps to create adaptive applications following the Material Design 3 guidelines.
version: 0.0.8
homepage: https://github.com/egortabula/material3_layout
repository: https://github.com/egortabula/material3_layout
issue_tracker: https://github.com/egortabula/material3_layout/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
screenshots:
  - description: 'This screenshot shows the thumbnail of the package'
    path: assets/material3_layout flutter package Egor Tabula.png

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.2
  flutter_lints: ^2.0.1
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.1
  riverpod_generator: ^2.2.1

flutter:
